version: '3.8'

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4.0-debian-11-r23
    networks:
      - kafka_net
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

  kafka-schema-registry:
    image: bitnami/schema-registry:6.0
    networks:
      - kafka_net
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_started
    environment:
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka:9092

networks:
  kafka_net:
    driver: bridge

volumes:
  kafka_data:

